language: node_js
node_js:
  - "0.10"
before_install:
  - chmod +x ./.travis/scripts/install_chrome.sh
  - chmod +x ./Cakefile
  - ./.travis/scripts/install_chrome.sh
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sudo google-chrome ./receiver.html"
  - "sudo google-chrome ./caller.html"
